#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get the new version from package.json
version=$(node -p "require('./package.json').version")

# Create version tag and latest tag
git tag "v$version"
# Check if latest tag exists and delete it if it does
if git rev-parse -q --verify refs/tags/latest >/dev/null; then
    git tag -d "latest"
fi
# Create latest tag
git tag "latest"

# Force push the tags
git push --tags -f