#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Path to package.json
PACKAGE_PATH="package.json"

# Check if package.json exists
if [ -f "$PACKAGE_PATH" ]; then
    # Extract current version number
    CURRENT_VERSION=$(grep -oP '(?<="version": ")[0-9]+\.[0-9]+\.[0-9]+(?=")' "$PACKAGE_PATH")
    

    if [ ! -z "$CURRENT_VERSION" ]; then
        # Split version into major.minor.patch
        MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
        MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
        PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
        
        # Increment patch version
        NEW_PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
        
        # Update only the version line in the file, preserving formatting
        sed -i -E "s/([ ]*\"version\": \")[0-9]+\.[0-9]+\.[0-9]+(\")$/\1$NEW_VERSION\2/" "$PACKAGE_PATH"
    fi
    
    # Add the modified files to git
    git add "$PACKAGE_PATH"
    git add package-lock.json
fi
